{% set name = "perl-yaml-libyaml" %}
{% set version = "0.86" %}
{% set sha256 = "b139675326591c95d2e431be8d8dd13fd87080b5826716de99879fc5e614f9d8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/I/IN/INGY/YAML-LibYAML-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win]
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
    - m2-make  # [win]
  host:
    - perl
  run:
    - perl

test:
  imports:
    - YAML::XS            # YAML::LibYAML is not imported directly

about:
  home: https://github.com/ingydotnet/yaml-libyaml-pm
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: Perl YAML Serialization using XS and libyaml

extra:
  recipe-maintainers:
    - xileF1337
    - cbrueffer
