{% set name = "perl-yaml-libyaml" %}
{% set version = "0.906.0" %}
{% set sha256 = "6bef4b8e7cea72730e23a7f800da6a6f5818b13c04a0658b9d56466ec28d10b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TI/TINITA/YAML-LibYAML-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - m2-make  # [win]
  host:
    - perl
  run:
    - perl

test:
  imports:
    - YAML::XS
    # YAML::LibYAML is not imported directly

about:
  home: "https://github.com/ingydotnet/yaml-libyaml-pm"
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
  summary: "Perl YAML Serialization using XS and libyaml."
  dev_url: "https://github.com/ingydotnet/yaml-libyaml-pm"
  doc_url: "https://metacpan.org/dist/YAML-LibYAML"

extra:
  recipe-maintainers:
    - conda-forge/perl-packagers
    - xileF1337
    - cbrueffer
